# Generated by Django 5.2 on 2025-04-30 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='deals.deal')),
            ],
        ),
        migrations.CreateModel(
            name='UPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='deals.deal')),
            ],
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='deals.deal')),
            ],
        ),
    ]
