# Generated by Django 5.2 on 2025-04-30 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('incoming', 'Приход'), ('outgoing', 'Расход')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='TransportProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.transport')),
            ],
        ),
        migrations.AddField(
            model_name='transport',
            name='products',
            field=models.ManyToManyField(through='logistics.TransportProduct', to='catalog.product'),
        ),
    ]
