# Generated by Django 5.2 on 2025-05-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='type',
            field=models.CharField(choices=[('incoming', 'Приход'), ('outgoing', 'Расход')], default='incoming', max_length=50),
        ),
    ]
